import { IsEmail, IsString, Length } from 'class-validator';
import {
  IsUppercase,
  IsLowercase,
  IsNumber,
  IsSpecialCharacter,
} from '../validators/custom-validators';
import { ApiProperty } from '@nestjs/swagger';
export class CreateUserDto {
  @ApiProperty({
    example: 'user@example.com',
    description: 'The email of the user',
  })
  @IsEmail()
  email: string;

  @ApiProperty({
    example: 'Password123!',
    description: 'The password of the user',
  })
  @IsString()
  @Length(8, 100)
  @IsUppercase({
    message: 'Your password must contain at least one uppercase letter',
  })
  @IsLowercase({
    message: 'Your password must contain at least one lowercase letter',
  })
  @IsNumber({ message: 'Your password must contain at least one number' })
  @IsSpecialCharacter({
    message: 'Your password must contain at least one special character',
  })
  password: string;
}

export class CreateGoogleUserDto {
  @ApiProperty({
    example: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlMzcxNzMwZWY4NmViYTI5YTUyM...',
    description: 'The token generated by firebase auth google',
  })
  @IsString()
  token: string;
}
